### ISSUE TITLE
Creation of QR for Handwritten prescriptions of a mid  level, legible handwriting using optimal code, 

### ISSUE THREAD

**Issue by V-M-Tejus** [V-M-Tejus/Py-Codes#6]
I want a python program which can create a QR for a Given input handwritten file which will be a prescription, I want a logo also in middle of the QR, A code is needed to decode it back and fetch data from qr, I will post that as a seperate issue, The person assigned this question only will get accepted for the decoding issue also 

Syntax:

<The basic one line explanation of code>
<Modules to Install>
<The file format input or template defined>
<The Working of each functtion used inside the code><can be inline comments or a seperate paragraph also >
<No personal details to be used in the program, Only arbitrary name and other medicine details have to be given as Sample>

**Comment by rabroldan** [comment]
Hi there can I take this one? I do want to ask as well when you say hand written. since Fetching the data through QR code will be a different separated issue as mentioned 

is this the process we wanted?

1. Hand written note
2. converted to text
3. text converting to QR code?

Where we we have QR code as the final piece and also What Logo do we want to place in the middle?

**Comment by V-M-Tejus** [comment]
Yes you are right

**Comment by V-M-Tejus** [comment]
Would you like to take it up ? 
@rabroldan

**Comment by rabroldan** [comment]
yes ill take it

**Comment by V-M-Tejus** [comment]
@rabroldan assigned to you

all the best
